WebApplication1/Models/FileModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace WebApplication1.Models
{
    public class FileModel
    {
        // what will be displayed
        [Display(Name = "File Name")]
        public string FileName { get; set; }

        // allows communication between server and user
        [Required(ErrorMessage = "Please select file.")]
        [Display(Name = "Browse File")]
        public HttpPostedFileBase[] Files { get; set; }
    }
}

WebApplication1/Controllers/DownloadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class DownloadController : Controller
    {
        // GET: Download
        public ActionResult FilePage()
        {

            string[] filePathImage = Directory.GetFiles(Server.MapPath("~/App_Data/Images/"));
            string[] filePathDocument = Directory.GetFiles(Server.MapPath("~/App_Data/Documents/"));
            string[] filePathVideo = Directory.GetFiles(Server.MapPath("~/App_Data/Videos/"));

            //Copy File names to Model collection.
            //The return below returns to the list here.

            List<FileModel> files = new List<FileModel>();

            foreach (string filePath in filePathImage)
            {
                files.Add(new FileModel { FileName = Path.GetFileName(filePath) });

            }

            foreach (string filePath in filePathDocument)
            {
                files.Add(new FileModel { FileName = Path.GetFileName(filePath) });

            }

            foreach (string filePath in filePathVideo)
            {
                files.Add(new FileModel { FileName = Path.GetFileName(filePath) });

            }

            return View(files);
            
        }

        public FileResult DownloadFile(string fileName) 
        {
            //Build the File Path.

            
            string path = Server.MapPath("~/App_Data/Images/") + fileName;
            byte[] bytes = System.IO.File.ReadAllBytes(path);

            //not working
            // for documents
            string pathd = Server.MapPath("~/App_Data/Documents/") + fileName;
            byte[] bytesd = System.IO.File.ReadAllBytes(pathd);

            // for videos
            string pathv = Server.MapPath("~/App_Data/Videos/") + fileName;
            byte[] bytesv = System.IO.File.ReadAllBytes(pathv);




            return File(bytes, "application/octet-stream", fileName);
           
        }


        public ActionResult DeleteFile(string fileName)
        {
            //Delete requires reading the files and then the allocation of a file path.
            //The file is then deleted based on the identified file path.

            //for images
            string path = Server.MapPath("~/App_Data/Images/") + fileName;
            byte[] bytes = System.IO.File.ReadAllBytes(path);

            //not working
            // for documents
            string pathd = Server.MapPath("~/App_Data/Documents/") + fileName;
            byte[] bytesd = System.IO.File.ReadAllBytes(pathd);

            //not working
            // for videos
            string pathv = Server.MapPath("~/App_Data/Videos/") + fileName;
            byte[] bytesv = System.IO.File.ReadAllBytes(pathv);

            //deleting files
            System.IO.File.Delete(path);

            //not working
            System.IO.File.Delete(pathd);
            System.IO.File.Delete(pathv);

            return RedirectToAction("FilePage");
        }
    }
}

WebApplication1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(HttpPostedFileBase Files) //INSIDE HOME
        {
            // Verify that the user selected a file
            // Not null and has a length

                if (Files != null && Files.ContentLength > 0)
            {

                // get file name
                var fileName = Path.GetFileName(Files.FileName);

                if (Request["ntype"] == "nDocument")
                {
                    // storing the file inside ~/App_Data/Documents folder
                    var path = Path.Combine(Server.MapPath("~/App_Data/Documents"), fileName);
                    Files.SaveAs(path);

                }

                if (Request["ntype"] == "nImage")
                {
                    // storing the file inside ~/App_Data/Images folder
                    var path = Path.Combine(Server.MapPath("~/App_Data/Images"), fileName);
                    Files.SaveAs(path);

                }

                if (Request["ntype"] == "nVideo")
                {
                    // storing the file inside ~/App_Data/Videos folder
                    var path = Path.Combine(Server.MapPath("~/App_Data/Videos"), fileName);
                    Files.SaveAs(path);

                }
            }
            // redirect back to the index action to show the form once again

            return RedirectToAction("Index");
        }

        public ActionResult About()
        {
            return View();
        }

    }
}

WebApplication1/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class ImageController : Controller
    {
        // GET: Image
        public ActionResult Index()
        {
            string[] filePaths = Directory.GetFiles(Server.MapPath("~/App_Data/Images/"));

            //Copy File names to Model collection.
            //The return below returns to the list here.

            List<FileModel> files = new List<FileModel>();

            foreach (string filePath in filePaths)
            {
                files.Add(new FileModel { FileName = Path.GetFileName(filePath) });
            }
            return View(files);

        }

        public FileResult DownloadFile(string fileName) 
        {
            //Build the File Path.
            string path = Server.MapPath("~/App_Data/Images/") + fileName;

            //Read the File data into Byte Array.
            byte[] bytes = System.IO.File.ReadAllBytes(path);

            //Send the File to Download.
            return File(bytes, "application/octet-stream", fileName);
        }

        public ActionResult DeleteFile(string fileName)
        {
            //Delete requires reading the files and then the allocation of a file path.
            //The file is then deleted based on the identified file path.

            string path = Server.MapPath("~/App_Data/Images/") + fileName;
            byte[] bytes = System.IO.File.ReadAllBytes(path);

            System.IO.File.Delete(path);

            return RedirectToAction("Index");
        }

    }
}

WebApplication1/Controllers/VideoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;
using System.IO;

namespace WebApplication1.Controllers
{
    public class VideoController : Controller
    {
        // GET: Video
        public ActionResult Index()
        {
            string[] filePaths = Directory.GetFiles(Server.MapPath("~/App_Data/Videos/"));

            //Copy File names to Model collection.
            //The return below returns to the list here.

            List<FileModel> files = new List<FileModel>();

            foreach (string filePath in filePaths)
            {
                files.Add(new FileModel { FileName = Path.GetFileName(filePath) });
            }
            return View(files);

        }

        public FileResult DownloadFile(string fileName)
        {
            //Build the File Path.
            string path = Server.MapPath("~/App_Data/Videos/") + fileName;

            //Read the File data into Byte Array.
            //Use a byte array becasue of octet-stream.
            byte[] bytes = System.IO.File.ReadAllBytes(path);

            //Send the File to Download.
            return File(bytes, "application/octet-stream", fileName);
        }

        public ActionResult DeleteFile(string fileName)
        {
           
            // getting path of file and storing byte array
            string path = Server.MapPath("~/App_Data/Videos/") + fileName;
            byte[] bytes = System.IO.File.ReadAllBytes(path);

            System.IO.File.Delete(path);

            return RedirectToAction("Index");
        }
    }
}

WebApplication1/Views/Download/FilePage.cshtml
@using WebApplication1.Models
@model List<FileModel>
@{
    ViewBag.Title = "FilePage";
}


<head>
    <style type="text/css">
        .auto-style {
            color: #FFFFFF;
        }

        .t {
            text-align: center;
            vertical-align: middle;
        }
    </style>
</head>
<div class="well-sm">
    <h3>File Page</h3>
    <h5>File Page to download and delete files</h5>
</div>


<div style="height: 400px; overflow: auto; background-color:lightgrey">
    <div class="well-sm">
        <table class="table table-condensed table-hover">
            <thead style="position: sticky;top: 0">
                <tr bgcolor="#222222" class="auto-style">
                    <th class="col-lg-8">File Name</th>
                    <th class="t, col-lg-2">DOWNLOAD</th>
                    <th class="t, col-lg-2">DELETE</th>
                </tr>
            </thead>
            @foreach (FileModel file in Model)
            {
                <tr>
                   

                    <td>@file.FileName</td>
                    <td>
                        <button class="btn btn-success">
                            @Html.ActionLink("Download", "DownloadFile",
                             new { fileName = file.FileName })
                        </button>
                    </td>
                    <td>
                        <button class="btn btn-danger">
                            @Html.ActionLink("DELETE", "DeleteFile",
                           new { fileName = file.FileName },
                           new { onclick = "return confirm('Are you sure you wish to delete this?');" })
                        </button>
                    </td>
                </tr>
            }
        </table>
    </div>
</div>

WebApplication1/Views/Home/About.cshtml
@{
    ViewBag.Title = "About Me";
}
<h3>About Me</h3>
<h5>Something About Me</h5>


<div class="container-fluid" style="background-color:lightgrey;">
    <div class="col-lg-6">
        <h4>Bio</h4>
        <p> I am Sinenhlanhla Dlamini,u19028386 a second year student at the University of Pretoria</p>
        <p>I have been programming since 2016, grade 10 at high and I have loved programming since then</p>
        <p>The field of IT has been very intresting and innovative.</p>
        <p>Hoping to finish the degree in record time, because I am excited to start working in the cooporate side.</p>
    </div>

    <div class="col-lg-6">
        <h4>Sinenhlanhla</h4>
        <img src="~/NewFolder1/20220406_170906.jpg" style="max-height : 150px; max-width : 180px;">
    </div>
</div>

WebApplication1/Views/Home/Index.cshtml
@using WebApplication1.Models
@{

    ViewBag.Title = "Home Page";
}


<div class="well-sm">
    <div class="form-horizontal">
        @using (Html.BeginForm("Index", "Home", FormMethod.Post, new { enctype = "multipart/form-data" }))


        {
            <h3>Home Page</h3>
            <h5>My home page</h5>
            <div class="container-fluid" style="background-color:lightgrey;">
                <div class="col-lg-6">
                    <h4>Description</h4>
                    <div>
                        <p>This system allows users to upload files, images of video of their choice and be able to delete and download them as well.</p>
                        <p>It allows the user to click on the radio button of their chose to pick the type of file they like to upload.</p>
                        <p>Users will then be directed to desired page to upload or delete file of chose.</p>

                    </div>

                </div>

                <div class="col-lg-6">
                    <h4>Option Selection</h4>

                    <div>

                        <label for="nDocument">Document</label>
                        <input type="radio" id="mDocument" name="ntype" value="nDocument"><br />

                        <label for="nDocument">Image</label>
                        <input type="radio" id="mImage" name="ntype" value="nImage"><br />

                        <label for="nVideo">Video</label>
                        <input type="radio" id="mVideo" name="ntype" value="nVideo"><br />

                        <div>
                        <input type="file" name="files" value="Browse" id="browse" />
                        </div>

                        <br />
                        <div>
                        <input type="submit" value="Submit" id="submit1" />
                        </div>

                    </div>
                </div>
            </div>
        }
    </div>
</div>

WebApplication1/Views/Image/Index.cshtml
@using WebApplication1.Models
@model List<FileModel>
@{
    ViewBag.Title = "Images";
}

<h3>Images</h3>
<h5>This view is for display, downloading and deleting images</h5>
<div class="container-fluid">
    <div class="col-lg-4">

            @foreach (FileModel file in Model)
            {
        <div>
            <img src="~/App_Data/Images/@file.FileName">

            <h5>@file.FileName</h5>

            <button class="btn btn-success">
                @Html.ActionLink("Download", "DownloadFile",
                 new { fileName = file.FileName })
            </button>


            <button class="btn btn-danger">
                @Html.ActionLink("DELETE", "DeleteFile",
               new { fileName = file.FileName },
               new { onclick = "return confirm('Are you sure you wish to delete this?');" })
            </button>
        </div>

            }
        </div>

    </div>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("HOME", "Index", "Home")</li>
   
                            <ul class="nav navbar-nav">

                                <li>@Html.ActionLink("File", "FilePage", "Download")</li>
                                <li>@Html.ActionLink("Image", "Index", "Image")</li>
                                <li>@Html.ActionLink("Videos", "Index", "Video")</li>
                                <li>@Html.ActionLink("About Me", "About", "Home")</li>

                            </ul>
                      
                    </ul>
                </div>
            </div>
        </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebApplication1/Views/Video/Index.cshtml
@using WebApplication1.Models
@model List<FileModel>
@{
    ViewBag.Title = "Videos";
}

<h3>Videos</h3>
<h5>This view is for display, downloading and deleting videos</h5>


<div class="container-fluid">
    <div class="col-lg-4">
        @foreach (FileModel file in Model)
        {

        <div>
            <video src="~/App_Data/Videos/@file.FileName" />

            <h5>@file.FileName</h5>

            <button class="btn btn-success">
                @Html.ActionLink("Download", "DownloadFile",
                 new { fileName = file.FileName })
            </button>


            <button class="btn btn-danger">
                @Html.ActionLink("DELETE", "DeleteFile",
               new { fileName = file.FileName },
               new { onclick = "return confirm('Are you sure you wish to delete this?');" })
            </button>
        </div>
            


        }
    </div>
</div>